name: deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesives/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist